version: '3.7'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=checkup
    volumes:
      - checkup_pg_data:/bitnami/postgresql

volumes:
  checkup_pg_data:
